### ISSUE TITLE
message-id format V1.1 clarification

### ISSUE THREAD

**Issue by DaveSenn** [stomp/stomp-spec#75]
The specification V1.1 does not describe a specific format for the message-id filed.
What is the correct format for message-id?

Ps.
I’m asking because I’ve problems with the message-id format when sending messages to a RabbitMQ Broker using Apache.NMS.STOMP library and I do not know which of the two is handling the id correctly.

**Comment by LionelCons** [comment]
The STOMP specification does not document the format the `message-id` header. This is broker specific.

From the client point of view, the `message-id` header should be seen as an opaque token that can be found in a `MESSAGE` frame and used in an `ACK` frame.
