### ISSUE TITLE
clarify content-length inclusion of null byte

### ISSUE THREAD

**Issue by stakach** [stomp/stomp-spec#83]
currently writing an implementation for crystal lang however not sure if the content-length header should include the terminating null byte.

I can see the python client does not include this byte in the length: https://github.com/jasonrbriggs/stomp.py/blob/3840e53c307e4dcb012bace0c0fb0c2b67d25104/stomp/utils.py#L287

However an example in the specification does include the null byte in the length calculation
http://stomp.github.io/stomp-specification-1.2.html#ERROR

currently I'm including it

**Comment by LionelCons** [comment]
The `content-length` header indicates the length of the message body so it should not include the NULL byte, which is not part of the body.

I will fix the example in the specification.

**Comment by LionelCons** [comment]
The example in the specification has been fixed.
