### ISSUE TITLE
Website moved by GitHub; links to old site are semi-broken

### ISSUE THREAD

**Issue by all-is-to-be-dared** [stomp/stomp-spec#84]
Because of GitHub changing GitHub Pages locations, it's now located at [stomp.github.io](stomp.github.io) instead of [stomp.github.com](stomp.github.com).

Specifically ran into this on the [IANA WebSocket Protocol Registries](https://www.iana.org/assignments/websocket/websocket.xml) page; the links it has to all three versions of the specification are still pointing to the old domain.

**Comment by jmesnil** [comment]
I've reached out to [iana@iana.org](mailto:iana@iana.org) to update the links. I'll update this issue when I got a reply from them

**Comment by jmesnil** [comment]
The file has been updated and the links works fine now: https://www.iana.org/assignments/websocket/websocket.xhtml

**Comment by LionelCons** [comment]
Thanks Jeff!
